# Generated by Django 5.0 on 2024-02-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_details',
        ),
    ]
