# Generated by Django 5.0 on 2024-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=180)),
                ('movie_id', models.CharField(default='', max_length=180)),
                ('url', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=800)),
                ('director', models.CharField(default='', max_length=200)),
                ('writers', models.CharField(default='', max_length=200)),
                ('genre', models.CharField(default='', max_length=200)),
                ('streming', models.CharField(default='', max_length=200)),
                ('username', models.CharField(default='', max_length=200, unique=True)),
            ],
            options={
                'db_table': 'watchlist_details',
            },
        ),
    ]
