# Generated by Django 5.0 on 2024-02-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='streming',
            new_name='streaming',
        ),
    ]
