# Generated by Django 5.0 on 2024-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_streming_watchlist_streaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
