data_line1=[ {'name': 'hidden1','id':'movie1','genre':'Action','url':'../static/images/movies/movie1.jpg'},
    {'name': 'hidden2','id':'movie2','genre':'Romance & Fiction','url':'../static/images/movies/movie2.jpg'},
    {'name': 'hidden3','id':'movie3','genre':'Action','url':'../static/images/movies/movie3.jpg'},
    {'name': 'hidden4','id':'movie4','genre':'Action','url':'../static/images/movies/movie4.jpg'},
    {'name': 'hidden5','id':'movie5','genre':'Action','url':'../static/images/movies/movie5.jpg'},
    # {'name': 'hidden4','id':'movie4','genre':'drama'},
    # {'name': 'hidden5','id':'movie5','genre':'fantasy'},
    # {'name': 'hidden6','id':'movie6','genre':'mystery'},
    # {'name': 'hidden7','id':'movie7','genre':'romance'},
    # {'name': 'hidden8','id':'movie8','genre':'thriller'},
    # {'name': 'hidden9','id':'movie9','genre':'documentary'},
    # {'name': 'hidden10','id':'movie10','genre':'science-fiction'},
    # {'name': 'hidden11','id':'movie11','genre':'historical'},
    # {'name': 'hidden12','id':'movie12','genre':'crime'},
]