data_line1=[ 
    {   
        'movie_name':'eagle',
        'name': 'hidden1','id':'movie1','genre':'Action & Thriller','url':'../static/images/movies/movie1.jpg', 
        'desc':'A journalist uncovers the story of a ruthless assassin when she investigates a government cover up.',
        'director':'Karthik Gattamneni',
        'streaming':'prime video',
        'writers':'Karthik Gettamneni and Manibabu Karanam',
        'index':1,
        'rating':"for 2k reviews 4.2/5",
    },
    {
        'movie_name':'Guntur Karam',
        'name': 'hidden2','id':'movie2','genre':'Action , Family & Drama','url':'../static/images/movies/movie2.jpg',
        'desc':'Years after his mother abandons him and remarries, a man demands answers when he is asked to sign a document denying.',
        'director':'Trivikram Srinivas',
        'streaming':'Netflix',
        'writers':'Trivikram Srinivas',
        'index':2,
        'rating':"for 1.7k reviews 4.1/5",
     },
    {
        'movie_name':'rrr',
        'name': 'hidden3','id':'movie3','genre':'Action, Adventure & Drama','url':'../static/images/movies/movie3.jpg',
        'desc':'A fearless warrior on a perilous mission comes face to face with a steely cop serving British.',
        'director':'S.S. Rajamouli',
        'streaming':'Netflix, Diney+ Hotstar & Zee 5',
        'writers':'Vijayendra Prasad, S.S. Rajamouli, Sai Madhav Burra',
        'index':3,
        'rating':"for 0.8k reviews 4.5/5",
    },
    {
        'movie_name':'bahubali 1',
        'name': 'hidden4','id':'movie4','genre':'Action & Drama','url':'../static/images/movies/movie4.jpg',
        'desc':'A child from the Mahishmati kingdom is raised by tribal people and one day learns about his royal heritage, his fathers bravery in battle.',
        'director':'S.S. Rajamouli',
        'streaming':'Netflix, Diney+ Hotstar & Sony Liv',
        'writers':'RajamouliC.H & Vijay Kumar',
        'index':4,
        'rating':"for 1.6k reviews 4.7/5",
    },
    {
        'movie_name':'bahubali 2',
        'name': 'hidden5','id':'movie5','genre':'Action & Drama','url':'../static/images/movies/movie5.jpg',
        'desc':'Amarendra Baahubali, the heir apparent to the throne of Mahishmati, finds his life and relationships endangered as his adoptive brother Bhallaladeva.',
        'director':'S.S. Rajamouli',
        'streaming':'Netflix, Diney+ Hotstar & Sony Liv',
        'writers':'RajamouliC.H & Vijay Kumar',
        'rating':"for 1.2k reviews 4.7/5",

    },
]
data_line2=[ 
    {   
        'movie_name':'salar',
        'name': 'hidden6','id':'movie6','genre':'Action, Crime & Drama','url':'../static/images/movies/movie6.jpg', 
        'desc':'The fate of a violently contested kingdom hangs on the fraught bond between two friends-turned-foes in this saga of power.',
        'director':'Prashanth Neel',
        'streaming':'Netflix',
        'writers':'Prashanth Neel',
        'index':6,
        'rating':"for 2k reviews 4.8/5",
    },
    {
        'movie_name':'radhe shyam',
        'name': 'hidden7','id':'movie7','genre':'Romance & Drama','url':'../static/images/movies/movie7.jpg',
        'desc':'Love blooms between a doctor with an uncertain future and a renowned palmist who thought he would never find love.',
        'director':'K.K. Radhakrishna Kumar',
        'streaming':'Netflix & Zee5',
        'writers':'Hussain Dalal & Madhan Karky',
        'index':7,
        'rating':"for 2.4k reviews 4.2/5",
     },
    {
        'movie_name':'hanuman',
        'name': 'hidden8','id':'movie8','genre':'Action, Adventure and fantasy','url':'../static/images/movies/movie8.jpg',
        'desc':'An imaginary place called Anjanadri where the protagonist gets the powers of Hanuman and fights for Anjanadri.',
        'director':'Prasanth Varma',
        'streaming':'In Theatres only',
        'writers':'Prasanth Varma',
        'index':8,
        'rating':"for 1.3k reviews 4.2/5",
    },
    {
        'movie_name':'saaho',
        'name': 'hidden9','id':'movie9','genre':'Action & Thriller','url':'../static/images/movies/movie9.jpg',
        'desc':'An undercover cop becomes embroiled in a battle with warring criminals who want to acquire a "black box," their ultimate key.',
        'director':'Sujeeth',
        'streaming':'Netflix & Prime Video',
        'writers':'Sujeeth, K.G.R Ashok & Abbas Dalal',
        'index':9,
        'rating':"for 1k reviews 3.8/5",
    },
    {
        'movie_name':'arjun reddy',
        'name': 'hidden10','id':'movie10','genre':'Action, Romance & Drama','url':'../static/images/movies/movie10.jpg',
        'desc':'Arjun Reddy, a short-tempered house surgeon, gets used to drugs and drinks when his girlfriend is forced to marry another person.',
        'director':'Sandeep Reddy Vanga',
        'streaming':'Diney+ Hotstar & prime video',
        'writers':'Sandeep Reddy Vanga, Mandela Pedaswamy',
        'index':10,
        'rating':"for 2.7k reviews 4.5/5",
    },
]
data_line3=[ 
    {   
        'movie_name':'animal',
        'name': 'hidden11','id':'movie11','genre':'Action, Crime & Drama','url':'../static/images/movies/movie11.jpg', 
        'desc':'The hardened son of a powerful industrialist returns home after years abroad and vows to take bloody his fathers life.',
        'director':'Sandeep Reddy Vanga',
        'streaming':'Netflix',
        'writers':'Pranay Reddy Vanga',
        'index':11,
        'rating':"for 2.7k reviews 4.5/5",
    },
    {
        'movie_name':'Blade Runner 2049',
        'name': 'hidden12','id':'movie12','genre':'Action, Mystery & Drama','url':'../static/images/movies/movie12.jpg',
        'desc':'Young Blade Runner K "s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.',
        'director':'Denis Villeneuve',
        'streaming':'Netflix,Jio cinema & prime video',
        'writers':'Hampton Fancher, Michael GreenPhilip & K. Dick',
        'index':12,
        'rating':"for 2.2k reviews 4.2/5",
     },
    {
        'movie_name':'DJ Till2',
        'name': 'hidden13','id':'movie13','genre':'Comedy and Drama','url':'../static/images/movies/movie13.jpg',
        'desc':'Follow Tillu as his life is upended by a mysterious murder, plunging him into a perilous discovery and danger.',
        'director':'Mallik Ram',
        'streaming':'In Theatres only',
        'writers':'Ravi Anthony, Sidhu Jonnalagadda',
        'index':13,
        'rating':"for 1.1k reviews 4.3/5",
    },
    {
        'movie_name':'Godzilla X Kong',
        'name': 'hidden14','id':'movie14','genre':'Adventure & Scifi','url':'../static/images/movies/movie14.jpg',
        'desc':'Two ancient titans, Godzilla and Kong, clash in an epic battle as origins and connection to Skull Islands mysteries.',
        'director':'Adam Wingard',
        'streaming':'Only in theatres',
        'writers':'Terry RossioSimon Barrett, Jeremy Slate',
        'index':14,
        'rating':"for 1.3k reviews 4.6/5",
    },
    {
        'movie_name':'Dune',
        'name': 'hidden15','id':'movie15','genre':'Adventure & Drama','url':'../static/images/movies/movie15.jpg',
        'desc':'A noble family becomes embroiled in a war for control over the galaxy most valuable asset while its heir a dark future.',
        'director':'Denis Villeneuve',
        'streaming':'Diney+ Hotstar & prime video',
        'writers':'Jon SpaihtsDenis Villeneuve, Eric Roth',
        'index':15,
        'rating':"for 1.7k reviews 3.9/5",
    },
]